// ========== 食材データ ==========
const INGREDIENTS = [
    // 肉類
    { id: 'chicken', name: '鶏肉', emoji: '🍗', category: 'meat' },
    { id: 'pork', name: '豚肉', emoji: '🥩', category: 'meat' },
    { id: 'beef', name: '牛肉', emoji: '🥩', category: 'meat' },
    { id: 'ground-meat', name: 'ひき肉', emoji: '🍖', category: 'meat' },
    { id: 'bacon', name: 'ベーコン', emoji: '🥓', category: 'meat' },
    { id: 'ham', name: 'ハム', emoji: '🍖', category: 'meat' },
    { id: 'sausage', name: 'ウインナー', emoji: '🌭', category: 'meat' },

    // 魚介
    { id: 'salmon', name: 'サーモン', emoji: '🐟', category: 'fish' },
    { id: 'tuna-can', name: 'ツナ缶', emoji: '🥫', category: 'fish' },
    { id: 'shrimp', name: 'エビ', emoji: '🦐', category: 'fish' },
    { id: 'squid', name: 'イカ', emoji: '🦑', category: 'fish' },
    { id: 'shirasu', name: 'しらす', emoji: '🐟', category: 'fish' },

    // 野菜
    { id: 'onion', name: '玉ねぎ', emoji: '🧅', category: 'vegetable' },
    { id: 'cabbage', name: 'キャベツ', emoji: '🥬', category: 'vegetable' },
    { id: 'lettuce', name: 'レタス', emoji: '🥬', category: 'vegetable' },
    { id: 'tomato', name: 'トマト', emoji: '🍅', category: 'vegetable' },
    { id: 'carrot', name: 'にんじん', emoji: '🥕', category: 'vegetable' },
    { id: 'potato', name: 'じゃがいも', emoji: '🥔', category: 'vegetable' },
    { id: 'spinach', name: 'ほうれん草', emoji: '🥬', category: 'vegetable' },
    { id: 'moyashi', name: 'もやし', emoji: '🌱', category: 'vegetable' },
    { id: 'green-onion', name: 'ねぎ', emoji: '🧅', category: 'vegetable' },
    { id: 'garlic', name: 'にんにく', emoji: '🧄', category: 'vegetable' },
    { id: 'ginger', name: '生姜', emoji: '🫚', category: 'vegetable' },
    { id: 'mushroom', name: 'きのこ', emoji: '🍄', category: 'vegetable' },
    { id: 'eggplant', name: 'なす', emoji: '🍆', category: 'vegetable' },
    { id: 'pepper', name: 'ピーマン', emoji: '🫑', category: 'vegetable' },
    { id: 'cucumber', name: 'きゅうり', emoji: '🥒', category: 'vegetable' },
    { id: 'bean-sprouts', name: '豆苗', emoji: '🌱', category: 'vegetable' },
    { id: 'paprika', name: 'パプリカ', emoji: '🫑', category: 'vegetable' },
    { id: 'broccoli', name: 'ブロッコリー', emoji: '🥦', category: 'vegetable' },

    // 卵・乳製品
    { id: 'egg', name: '卵', emoji: '🥚', category: 'egg-dairy' },
    { id: 'cheese', name: 'チーズ', emoji: '🧀', category: 'egg-dairy' },
    { id: 'milk', name: '牛乳', emoji: '🥛', category: 'egg-dairy' },
    { id: 'butter', name: 'バター', emoji: '🧈', category: 'egg-dairy' },
    { id: 'yogurt', name: 'ヨーグルト', emoji: '🥛', category: 'egg-dairy' },
    { id: 'tofu', name: '豆腐', emoji: '🧊', category: 'egg-dairy' },

    // その他
    { id: 'rice', name: 'ごはん', emoji: '🍚', category: 'other' },
    { id: 'pasta', name: 'パスタ', emoji: '🍝', category: 'other' },
    { id: 'bread', name: 'パン', emoji: '🍞', category: 'other' },
    { id: 'udon', name: 'うどん', emoji: '🍜', category: 'other' },
    { id: 'soy-sauce', name: '醤油', emoji: '🫗', category: 'other' },
    { id: 'miso', name: '味噌', emoji: '🫘', category: 'other' },
    { id: 'kimchi', name: 'キムチ', emoji: '🥘', category: 'other' },
    { id: 'natto', name: '納豆', emoji: '🫘', category: 'other' },
    { id: 'mentsuyu', name: 'めんつゆ', emoji: '🫗', category: 'other' },
    { id: 'sesame-oil', name: 'ごま油', emoji: '🫒', category: 'other' },
    { id: 'mayonnaise', name: 'マヨネーズ', emoji: '🧴', category: 'other' },
    { id: 'ketchup', name: 'ケチャップ', emoji: '🧴', category: 'other' },
];

// ========== レシピデータ ==========
const RECIPES = [
    {
        id: 1,
        name: 'ふわとろ卵のチーズオムレツ',
        emoji: '🍳',
        time: 5,
        difficulty: 'かんたん',
        servings: '1人分',
        description: 'バターの香りが食欲をそそる、ふわとろ食感のチーズオムレツ。朝食やブランチにぴったり！',
        ingredients: ['egg', 'cheese', 'butter', 'milk'],
        ingredientDetails: [
            { name: '卵', amount: '3個', icon: '🥚' },
            { name: 'ピザ用チーズ', amount: '30g', icon: '🧀' },
            { name: 'バター', amount: '10g', icon: '🧈' },
            { name: '牛乳', amount: '大さじ2', icon: '🥛' },
            { name: '塩こしょう', amount: '少々', icon: '🧂' },
        ],
        steps: [
            {
                text: 'ボウルに卵を割り入れ、牛乳・塩こしょうを加えてよく混ぜます。空気を含ませるように、箸で切るように混ぜるのがコツ！',
                emoji: '🥣',
                tip: '混ぜすぎないのがふわふわのポイント。白身が少し残るくらいでOK',
            },
            {
                text: 'フライパンにバターを入れて中火で加熱。バターが溶けて泡立ちはじめたら、卵液を一気に流し入れます。',
                emoji: '🧈',
                tip: 'バターが焦げないように注意。薄い茶色になったらすぐ卵を入れて',
            },
            {
                text: '大きくかき混ぜながら半熟状にします。全体がトロッとしてきたら、中央にチーズをのせます。',
                emoji: '🧀',
                tip: '菜箸で大きく円を描くように3〜4回混ぜるだけ',
            },
            {
                text: 'フライパンの手前から奥に向かって三つ折りにし、お皿にスライドさせて完成！',
                emoji: '✨',
                tip: 'フライパンを傾けてお皿に滑らせるときれいに盛れます',
            },
        ],
        tips: [
            '卵は常温に戻してから使うとより均一に火が通ります',
            'チーズはモッツァレラに変えるとさらにとろ〜り',
            'ケチャップやパセリを添えると見栄えアップ',
        ],
    },
    {
        id: 2,
        name: '豚バラもやしのスタミナ炒め',
        emoji: '🥘',
        time: 7,
        difficulty: 'かんたん',
        servings: '2人分',
        description: 'にんにくと生姜の香りが効いた、ごはんがすすむスタミナおかず。もやしのシャキシャキ感が最高！',
        ingredients: ['pork', 'moyashi', 'garlic', 'ginger', 'soy-sauce', 'sesame-oil', 'green-onion'],
        ingredientDetails: [
            { name: '豚バラ薄切り', amount: '150g', icon: '🥩' },
            { name: 'もやし', amount: '1袋(200g)', icon: '🌱' },
            { name: 'にんにく', amount: '1片', icon: '🧄' },
            { name: '生姜', amount: '1片', icon: '🫚' },
            { name: '醤油', amount: '大さじ1.5', icon: '🫗' },
            { name: 'ごま油', amount: '大さじ1', icon: '🫒' },
            { name: 'ねぎ', amount: '適量', icon: '🧅' },
            { name: '砂糖', amount: '小さじ1', icon: '🧂' },
            { name: '塩こしょう', amount: '少々', icon: '🧂' },
        ],
        steps: [
            {
                text: '豚バラ肉を3cm幅に切ります。にんにく・生姜はみじん切りにします。',
                emoji: '🔪',
                tip: '豚肉は冷たいままの方が切りやすい',
            },
            {
                text: 'フライパンにごま油を引き、にんにく・生姜を弱火で炒めて香りを出します。',
                emoji: '🧄',
                tip: '焦がさないように弱火でじっくり。香りが立ったらOK',
            },
            {
                text: '中火に上げて豚肉を入れ、色が変わるまで炒めます。',
                emoji: '🥩',
                tip: '豚肉を広げて入れると均一に火が通ります',
            },
            {
                text: 'もやしを加えて強火でサッと30秒ほど炒め、醤油・砂糖・塩こしょうで味付けして完成！ねぎを散らして。',
                emoji: '🔥',
                tip: 'もやしは炒めすぎると水っぽくなるので、強火で一気に！',
            },
        ],
        tips: [
            '豆板醤を少し加えるとピリ辛でさらにごはんがすすむ',
            'もやしの代わりにキャベツや豆苗でもOK',
            '仕上げにごまをふると香ばしさアップ',
        ],
    },
    {
        id: 3,
        name: 'ツナとトマトの簡単パスタ',
        emoji: '🍝',
        time: 10,
        difficulty: 'ふつう',
        servings: '1人分',
        description: 'ツナ缶とトマトで作る、シンプルだけど味わい深いパスタ。ランチにぴったりの一皿。',
        ingredients: ['pasta', 'tuna-can', 'tomato', 'garlic', 'onion'],
        ingredientDetails: [
            { name: 'パスタ', amount: '100g', icon: '🍝' },
            { name: 'ツナ缶', amount: '1缶', icon: '🥫' },
            { name: 'トマト', amount: '1個', icon: '🍅' },
            { name: 'にんにく', amount: '1片', icon: '🧄' },
            { name: '玉ねぎ', amount: '1/4個', icon: '🧅' },
            { name: 'オリーブオイル', amount: '大さじ2', icon: '🫒' },
            { name: '塩こしょう', amount: '適量', icon: '🧂' },
        ],
        steps: [
            {
                text: '大きな鍋でたっぷりのお湯を沸かし、塩を入れてパスタを茹で始めます（袋の表示時間マイナス1分）。',
                emoji: '🫕',
                tip: 'お湯1Lに対して塩小さじ2が目安。しっかり塩味をつけて',
            },
            {
                text: 'パスタを茹でている間に、にんにくをみじん切り、玉ねぎを薄切り、トマトをざく切りにします。',
                emoji: '🔪',
                tip: 'トマトは湯むきしなくてOK。ざく切りで十分',
            },
            {
                text: 'フライパンにオリーブオイルとにんにくを入れて弱火で加熱。香りが出たら玉ねぎを炒め、しんなりしたらトマトを加えます。',
                emoji: '🍅',
                tip: 'トマトを潰しながら炒めるとソースになりやすい',
            },
            {
                text: 'ツナ缶を汁ごと加えて混ぜ、茹で上がったパスタと茹で汁少々を入れて絡めたら完成！',
                emoji: '✨',
                tip: '茹で汁を大さじ2くらい入れると、ソースがパスタによく絡みます',
            },
        ],
        tips: [
            'バジルやパセリを添えると本格的な仕上がりに',
            'チーズをかけるとコクが増して美味しい',
            'トマト缶でも代用OK。その場合は少し煮詰めて',
        ],
    },
    {
        id: 4,
        name: 'キムチチーズチャーハン',
        emoji: '🍳',
        time: 8,
        difficulty: 'かんたん',
        servings: '1人分',
        description: 'ピリ辛キムチととろけるチーズのやみつきチャーハン。残りごはんで簡単に作れる！',
        ingredients: ['rice', 'kimchi', 'egg', 'cheese', 'sesame-oil', 'green-onion'],
        ingredientDetails: [
            { name: 'ごはん', amount: '茶碗1.5杯', icon: '🍚' },
            { name: 'キムチ', amount: '80g', icon: '🥘' },
            { name: '卵', amount: '1個', icon: '🥚' },
            { name: 'ピザ用チーズ', amount: '30g', icon: '🧀' },
            { name: 'ごま油', amount: '大さじ1', icon: '🫒' },
            { name: 'ねぎ', amount: '適量', icon: '🧅' },
            { name: '醤油', amount: '小さじ1', icon: '🫗' },
        ],
        steps: [
            {
                text: 'キムチを食べやすい大きさに刻みます。ねぎは小口切りに。',
                emoji: '🔪',
                tip: 'キムチの汁も使うので捨てないで！旨味がたっぷり',
            },
            {
                text: 'フライパンにごま油を引き、キムチを中火で1分炒めて香りを出します。',
                emoji: '🥘',
                tip: 'キムチを先に炒めると香ばしさが出てワンランクアップ',
            },
            {
                text: 'ごはんを加えて強火で炒め、パラパラになったら醤油を回し入れます。フライパンの端に寄せて、空いたスペースで卵を炒り、全体を混ぜます。',
                emoji: '🍚',
                tip: 'ごはんを広げてから混ぜる、を繰り返すとパラパラに',
            },
            {
                text: '火を止めてチーズをのせ、蓋をして30秒。チーズがとろけたらねぎを散らして完成！',
                emoji: '🧀',
                tip: 'チーズは余熱で十分とろけます。加熱しすぎに注意',
            },
        ],
        tips: [
            'ベーコンやハムを足すとボリュームアップ',
            '卵黄をのせて崩しながら食べるのも美味',
            '仕上げに韓国のりを添えると本格的',
        ],
    },
    {
        id: 5,
        name: '鶏むね肉のレンジ蒸し',
        emoji: '🐔',
        time: 8,
        difficulty: 'かんたん',
        servings: '2人分',
        description: 'レンジだけで作れるしっとり鶏むね肉。ねぎだれをかければ立派なメインおかずに。',
        ingredients: ['chicken', 'green-onion', 'ginger', 'sesame-oil', 'soy-sauce'],
        ingredientDetails: [
            { name: '鶏むね肉', amount: '1枚(250g)', icon: '🍗' },
            { name: 'ねぎ', amount: '1/2本', icon: '🧅' },
            { name: '生姜', amount: '1片', icon: '🫚' },
            { name: 'ごま油', amount: '大さじ1', icon: '🫒' },
            { name: '醤油', amount: '大さじ1', icon: '🫗' },
            { name: '酒', amount: '大さじ1', icon: '🍶' },
            { name: '砂糖', amount: '小さじ1', icon: '🧂' },
            { name: '塩', amount: '少々', icon: '🧂' },
        ],
        steps: [
            {
                text: '鶏むね肉をフォークで数か所刺し、塩と酒をまぶして耐熱皿にのせます。ラップをふんわりかけます。',
                emoji: '🍗',
                tip: 'フォークで穴を開けると味が染み込みやすく、加熱ムラも防げる',
            },
            {
                text: '電子レンジ600Wで3分加熱。裏返してさらに2分加熱したら、ラップをしたまま3分蒸らします。',
                emoji: '📡',
                tip: '蒸らし時間が大事！余熱でじっくり火を通してしっとり仕上げ',
            },
            {
                text: '蒸らしている間にねぎだれを作ります。ねぎのみじん切り・おろし生姜・醤油・ごま油・砂糖を混ぜ合わせます。',
                emoji: '🧅',
                tip: 'ねぎは水にさらすと辛みが和らぎます',
            },
            {
                text: '鶏肉を食べやすい厚さにスライスし、お皿に並べてねぎだれをたっぷりかけて完成！',
                emoji: '✨',
                tip: '繊維を断つように斜めに切ると柔らかい食感に',
            },
        ],
        tips: [
            '鶏肉の厚い部分を開いて均一にすると加熱ムラが減る',
            'ポン酢＋ラー油のたれもおすすめ',
            '残ったら冷蔵庫で保存して翌日のサラダにも',
        ],
    },
    {
        id: 6,
        name: 'ベーコンエッグトースト',
        emoji: '🍞',
        time: 5,
        difficulty: 'かんたん',
        servings: '1人分',
        description: '食パンの上にベーコンと卵をのせて焼くだけ！忙しい朝にぴったりの朝食。',
        ingredients: ['bread', 'egg', 'bacon', 'cheese', 'mayonnaise'],
        ingredientDetails: [
            { name: '食パン', amount: '1枚', icon: '🍞' },
            { name: '卵', amount: '1個', icon: '🥚' },
            { name: 'ベーコン', amount: '1枚', icon: '🥓' },
            { name: 'チーズ', amount: '1枚', icon: '🧀' },
            { name: 'マヨネーズ', amount: '適量', icon: '🧴' },
            { name: '塩こしょう', amount: '少々', icon: '🧂' },
        ],
        steps: [
            {
                text: '食パンの端にマヨネーズで土手を作り、中央をスプーンの裏で軽くくぼませます。',
                emoji: '🍞',
                tip: 'マヨネーズの土手が卵の流出を防いでくれます',
            },
            {
                text: 'くぼみにベーコンを敷き、その上に卵を割り入れます。チーズをのせて塩こしょう。',
                emoji: '🥚',
                tip: '卵は低い位置からそっと落とすと黄身が割れにくい',
            },
            {
                text: 'トースター（1000W）で5分焼いて完成！卵の焼き加減はお好みで調整。',
                emoji: '🔥',
                tip: '半熟が好きなら4分、しっかり派は6分が目安',
            },
        ],
        tips: [
            'アボカドスライスをのせるとカフェ風に',
            'ケチャップやタバスコをかけても美味しい',
            'ベーコンの代わりにハムでもOK',
        ],
    },
    {
        id: 7,
        name: '豆腐と卵のふんわりスープ',
        emoji: '🥣',
        time: 7,
        difficulty: 'かんたん',
        servings: '2人分',
        description: 'やさしい味わいの中華風スープ。体があたたまる、ほっとする一杯。',
        ingredients: ['tofu', 'egg', 'green-onion', 'sesame-oil'],
        ingredientDetails: [
            { name: '絹ごし豆腐', amount: '1/2丁', icon: '🧊' },
            { name: '卵', amount: '1個', icon: '🥚' },
            { name: 'ねぎ', amount: '適量', icon: '🧅' },
            { name: 'ごま油', amount: '小さじ1', icon: '🫒' },
            { name: '鶏ガラスープの素', amount: '小さじ2', icon: '🧂' },
            { name: '水', amount: '400ml', icon: '💧' },
            { name: '片栗粉', amount: '小さじ1', icon: '🧂' },
            { name: '塩こしょう', amount: '少々', icon: '🧂' },
        ],
        steps: [
            {
                text: '鍋に水と鶏ガラスープの素を入れて火にかけ、沸騰させます。',
                emoji: '🫕',
                tip: '水から入れると素がダマにならずきれいに溶けます',
            },
            {
                text: '豆腐をスプーンですくって入れ、1分ほど煮ます。塩こしょうで味を調えます。',
                emoji: '🧊',
                tip: 'スプーンですくうと表面がなめらかで口当たりが良い',
            },
            {
                text: '片栗粉を同量の水で溶いて回し入れ、とろみをつけます。',
                emoji: '🥄',
                tip: 'とろみをつけてから卵を入れると、ふわっと仕上がる',
            },
            {
                text: '溶き卵を細く回し入れ、ふわっと浮いてきたらごま油をたらし、ねぎを散らして完成！',
                emoji: '✨',
                tip: '卵を入れたらすぐかき混ぜず、10秒待ってからやさしく混ぜて',
            },
        ],
        tips: [
            'ワカメやコーンを足しても美味しい',
            '仕上げに白ごまをふると風味アップ',
            'ラー油を垂らすと大人向けの味に',
        ],
    },
    {
        id: 8,
        name: 'ほうれん草とベーコンのバター炒め',
        emoji: '🥬',
        time: 5,
        difficulty: 'かんたん',
        servings: '2人分',
        description: 'バターの香りとベーコンの旨味がほうれん草に絡む、定番の副菜。',
        ingredients: ['spinach', 'bacon', 'butter', 'garlic', 'soy-sauce'],
        ingredientDetails: [
            { name: 'ほうれん草', amount: '1束', icon: '🥬' },
            { name: 'ベーコン', amount: '2枚', icon: '🥓' },
            { name: 'バター', amount: '10g', icon: '🧈' },
            { name: 'にんにく', amount: '1片', icon: '🧄' },
            { name: '醤油', amount: '小さじ1', icon: '🫗' },
            { name: '塩こしょう', amount: '少々', icon: '🧂' },
        ],
        steps: [
            {
                text: 'ほうれん草をよく洗い、4cm幅に切ります。ベーコンは1cm幅に切り、にんにくは薄切りに。',
                emoji: '🔪',
                tip: 'ほうれん草の根元は砂が入りやすいのでしっかり洗って',
            },
            {
                text: 'フライパンにバターとにんにくを入れて弱火で加熱。香りが立ったらベーコンを炒めます。',
                emoji: '🧈',
                tip: 'バターは焦げやすいので弱火でじっくり',
            },
            {
                text: 'ベーコンがカリッとしたら、ほうれん草の茎→葉の順に加えて強火でサッと炒めます。醤油を回しかけて完成！',
                emoji: '✨',
                tip: '茎と葉を時間差で入れると均一に火が通る',
            },
        ],
        tips: [
            'コーンを加えると彩りがきれいに',
            'しめじやエリンギなどのきのこを足しても合う',
            '醤油の代わりにポン酢でさっぱり仕上げても美味',
        ],
    },
    {
        id: 9,
        name: '納豆アボカド丼',
        emoji: '🥑',
        time: 3,
        difficulty: 'かんたん',
        servings: '1人分',
        description: '混ぜてのせるだけ！栄養満点のヘルシー丼。火を使わないから暑い日にもぴったり。',
        ingredients: ['rice', 'natto', 'egg', 'soy-sauce', 'sesame-oil'],
        ingredientDetails: [
            { name: 'ごはん', amount: '茶碗1杯', icon: '🍚' },
            { name: '納豆', amount: '1パック', icon: '🫘' },
            { name: '卵黄', amount: '1個分', icon: '🥚' },
            { name: '醤油', amount: '小さじ1', icon: '🫗' },
            { name: 'ごま油', amount: '小さじ1/2', icon: '🫒' },
            { name: 'ねぎ・のり', amount: '適量', icon: '🧅' },
        ],
        steps: [
            {
                text: '納豆に付属のたれとからしを入れてよく混ぜます。',
                emoji: '🫘',
                tip: '50回以上混ぜると粘りが増して旨味アップ！',
            },
            {
                text: 'ごはんの上に納豆をのせ、中央に卵黄を落とします。',
                emoji: '🥚',
                tip: '卵黄だけを使うと濃厚な味わいに',
            },
            {
                text: '醤油とごま油を回しかけ、ねぎとのりを散らして完成！',
                emoji: '✨',
                tip: 'よく混ぜてから食べると全体に味が行き渡る',
            },
        ],
        tips: [
            'アボカドを角切りにして加えると栄養価アップ',
            'キムチをのせるとピリ辛味変が楽しめる',
            'しらすを足すとカルシウム補給にも',
        ],
    },
    {
        id: 10,
        name: '簡単焼きうどん',
        emoji: '🍜',
        time: 8,
        difficulty: 'かんたん',
        servings: '1人分',
        description: '冷蔵庫の余り物でパパッと作れる焼きうどん。ソース味でやみつきに！',
        ingredients: ['udon', 'cabbage', 'pork', 'carrot', 'soy-sauce', 'sesame-oil'],
        ingredientDetails: [
            { name: 'うどん（茹で）', amount: '1玉', icon: '🍜' },
            { name: '豚バラ薄切り', amount: '80g', icon: '🥩' },
            { name: 'キャベツ', amount: '2枚', icon: '🥬' },
            { name: 'にんじん', amount: '1/4本', icon: '🥕' },
            { name: '醤油', amount: '大さじ1', icon: '🫗' },
            { name: 'ごま油', amount: '大さじ1', icon: '🫒' },
            { name: 'ウスターソース', amount: '大さじ1', icon: '🧴' },
            { name: 'かつお節', amount: '適量', icon: '🐟' },
        ],
        steps: [
            {
                text: 'キャベツをざく切り、にんじんを短冊切り、豚肉を3cm幅に切ります。',
                emoji: '🔪',
                tip: '野菜は薄めに切ると火が通りやすい',
            },
            {
                text: 'フライパンにごま油を引いて中火で豚肉を炒め、色が変わったら野菜を加えてさらに炒めます。',
                emoji: '🥩',
                tip: '豚肉から出る脂で野菜を炒めると旨味たっぷり',
            },
            {
                text: 'うどんを加え、水大さじ2をふりかけてほぐしながら炒めます。',
                emoji: '🍜',
                tip: '水を加えるとうどんがほぐれやすくなります',
            },
            {
                text: '醤油・ウスターソースを加えて全体を絡め、お皿に盛ってかつお節をのせたら完成！',
                emoji: '✨',
                tip: '仕上げに青のりを加えると風味がさらにアップ',
            },
        ],
        tips: [
            'もやしやピーマンなど冷蔵庫の残り野菜を何でも入れてOK',
            '目玉焼きをのせると満足感アップ',
            '焼きそばソースを使えばさらに簡単',
        ],
    },
    {
        id: 11,
        name: 'エビとブロッコリーのガーリック炒め',
        emoji: '🦐',
        time: 8,
        difficulty: 'ふつう',
        servings: '2人分',
        description: 'にんにくの香りが食欲をそそるプリプリエビとブロッコリーの炒めもの。おかずにもおつまみにも。',
        ingredients: ['shrimp', 'broccoli', 'garlic', 'butter', 'soy-sauce'],
        ingredientDetails: [
            { name: 'むきエビ', amount: '150g', icon: '🦐' },
            { name: 'ブロッコリー', amount: '1/2株', icon: '🥦' },
            { name: 'にんにく', amount: '2片', icon: '🧄' },
            { name: 'バター', amount: '10g', icon: '🧈' },
            { name: '醤油', amount: '小さじ1', icon: '🫗' },
            { name: '塩こしょう', amount: '少々', icon: '🧂' },
            { name: 'オリーブオイル', amount: '大さじ1', icon: '🫒' },
        ],
        steps: [
            {
                text: 'ブロッコリーを小房に分け、耐熱容器に入れて水大さじ1をふり、ラップをしてレンジ600Wで1分半加熱します。',
                emoji: '🥦',
                tip: 'レンジで下茹ですると時短になる。茹ですぎ注意',
            },
            {
                text: 'にんにくを薄切りにし、フライパンにオリーブオイルと一緒に弱火で加熱。きつね色になるまで炒めて取り出します。',
                emoji: '🧄',
                tip: 'にんにくチップは焦げやすいので目を離さないで',
            },
            {
                text: '同じフライパンでエビを中火で炒め、色が変わったらブロッコリーを加えます。',
                emoji: '🦐',
                tip: 'エビは炒めすぎると固くなるので、色が変わったらすぐ次へ',
            },
            {
                text: 'バターと醤油を加えて絡め、取り出したにんにくチップをのせて完成！',
                emoji: '✨',
                tip: 'バター醤油は焦がさないように火を弱めてから入れて',
            },
        ],
        tips: [
            'アスパラガスやパプリカを足すと彩り豊かに',
            '唐辛子を加えるとペペロンチーノ風に',
            'パスタの具材としてもアレンジ可能',
        ],
    },
    {
        id: 12,
        name: 'しらす丼',
        emoji: '🐟',
        time: 3,
        difficulty: 'かんたん',
        servings: '1人分',
        description: 'しらすをたっぷりのせた簡単丼。シンプルだけど旨味たっぷりで満足の一杯。',
        ingredients: ['rice', 'shirasu', 'egg', 'soy-sauce', 'green-onion'],
        ingredientDetails: [
            { name: 'ごはん', amount: '茶碗1杯', icon: '🍚' },
            { name: 'しらす', amount: '50g', icon: '🐟' },
            { name: '卵黄', amount: '1個分', icon: '🥚' },
            { name: '醤油', amount: '少々', icon: '🫗' },
            { name: 'ねぎ', amount: '適量', icon: '🧅' },
            { name: '大葉', amount: '2枚', icon: '🌿' },
        ],
        steps: [
            {
                text: 'あたたかいごはんを丼に盛ります。',
                emoji: '🍚',
                tip: 'ごはんは炊きたてがベスト！',
            },
            {
                text: 'しらすをたっぷりのせ、中央に卵黄を落とします。',
                emoji: '🐟',
                tip: 'しらすは惜しみなくたっぷりのせるのがポイント',
            },
            {
                text: '刻みねぎと千切りの大葉を散らし、醤油を回しかけて完成！',
                emoji: '✨',
                tip: '醤油は少なめに。しらすの塩気で十分',
            },
        ],
        tips: [
            '梅干しを添えるとさっぱり食べられる',
            'ごまをたっぷりふると風味アップ',
            '刻みのりをのせても美味しい',
        ],
    },
    {
        id: 13,
        name: 'なすとひき肉のピリ辛炒め',
        emoji: '🍆',
        time: 8,
        difficulty: 'ふつう',
        servings: '2人分',
        description: 'とろ〜りなすにピリ辛のひき肉が絡む、ごはんが止まらないおかず。麻婆なす風！',
        ingredients: ['eggplant', 'ground-meat', 'garlic', 'ginger', 'soy-sauce', 'sesame-oil', 'green-onion'],
        ingredientDetails: [
            { name: 'なす', amount: '2本', icon: '🍆' },
            { name: 'ひき肉（合い挽き）', amount: '150g', icon: '🍖' },
            { name: 'にんにく', amount: '1片', icon: '🧄' },
            { name: '生姜', amount: '1片', icon: '🫚' },
            { name: '醤油', amount: '大さじ1.5', icon: '🫗' },
            { name: 'ごま油', amount: '大さじ1', icon: '🫒' },
            { name: 'ねぎ', amount: '適量', icon: '🧅' },
            { name: '味噌', amount: '大さじ1', icon: '🫘' },
            { name: '砂糖', amount: '小さじ1', icon: '🧂' },
            { name: '豆板醤', amount: '小さじ1/2', icon: '🌶️' },
        ],
        steps: [
            {
                text: 'なすを乱切りにし、水に2分さらしてアク抜き。水気をしっかり拭きます。にんにく・生姜はみじん切り。',
                emoji: '🔪',
                tip: 'なすの水気をしっかり拭くと油ハネ防止＆味が染みやすい',
            },
            {
                text: 'フライパンにごま油を多めに引き、なすを中火で炒めて油を吸わせます。しんなりしたら一度取り出します。',
                emoji: '🍆',
                tip: 'なすは油をたっぷり吸うとトロトロ食感に',
            },
            {
                text: '同じフライパンでにんにく・生姜を炒め、ひき肉を加えてポロポロになるまで炒めます。',
                emoji: '🍖',
                tip: 'ひき肉はあまり動かさず焼き色をつけると香ばしい',
            },
            {
                text: 'なすを戻し、醤油・味噌・砂糖・豆板醤を合わせて加え、絡めたらねぎを散らして完成！',
                emoji: '✨',
                tip: '辛さが苦手な方は豆板醤を減らしてOK',
            },
        ],
        tips: [
            'ごはんにのせて丼にしても最高',
            'ピーマンやパプリカを加えると彩りアップ',
            '豆腐を入れると麻婆豆腐風にもアレンジ可能',
        ],
    },
    {
        id: 14,
        name: 'ハムチーズのホットサンド',
        emoji: '🥪',
        time: 5,
        difficulty: 'かんたん',
        servings: '1人分',
        description: 'フライパンで作るカリカリホットサンド。とろけるチーズとハムの黄金コンビ！',
        ingredients: ['bread', 'ham', 'cheese', 'butter'],
        ingredientDetails: [
            { name: '食パン（8枚切り）', amount: '2枚', icon: '🍞' },
            { name: 'ハム', amount: '2枚', icon: '🍖' },
            { name: 'スライスチーズ', amount: '1枚', icon: '🧀' },
            { name: 'バター', amount: '10g', icon: '🧈' },
        ],
        steps: [
            {
                text: '食パンの上にハム→チーズ→ハムの順にのせ、もう1枚のパンで挟みます。',
                emoji: '🥪',
                tip: 'チーズをハムで挟むと焼いたとき溶け出しにくい',
            },
            {
                text: 'フライパンにバターを溶かし、弱〜中火でサンドイッチを焼きます。ヘラやお皿で上から軽く押さえます。',
                emoji: '🧈',
                tip: 'アルミホイルを被せて上に鍋を置くとプレス効果バツグン',
            },
            {
                text: 'きつね色に焼けたら裏返し、同様に焼きます。両面カリッとしたら対角線に切って完成！',
                emoji: '✨',
                tip: '焼き色がつくまで2分くらい。じっくり待つのがコツ',
            },
        ],
        tips: [
            'マスタードを塗ると大人の味に',
            'トマトやレタスを挟んでも美味しい',
            'ケチャップを添えてブランチに',
        ],
    },
    {
        id: 15,
        name: 'きのこと豆腐の味噌汁',
        emoji: '🍲',
        time: 7,
        difficulty: 'かんたん',
        servings: '2人分',
        description: 'きのこの旨味たっぷり、ほっとする定番お味噌汁。毎日でも飲みたい一杯。',
        ingredients: ['tofu', 'mushroom', 'miso', 'green-onion'],
        ingredientDetails: [
            { name: '絹ごし豆腐', amount: '1/2丁', icon: '🧊' },
            { name: 'きのこ（しめじ等）', amount: '1/2パック', icon: '🍄' },
            { name: '味噌', amount: '大さじ2', icon: '🫘' },
            { name: 'ねぎ', amount: '適量', icon: '🧅' },
            { name: '顆粒だし', amount: '小さじ1', icon: '🧂' },
            { name: '水', amount: '400ml', icon: '💧' },
        ],
        steps: [
            {
                text: 'きのこの石づきを取り、小房に分けます。豆腐はさいの目に切ります。',
                emoji: '🔪',
                tip: 'きのこは洗わずに手でほぐすのがベスト',
            },
            {
                text: '鍋に水と顆粒だしを入れて火にかけ、沸騰したらきのこを加えて2分煮ます。',
                emoji: '🫕',
                tip: 'きのこは煮ると旨味が出るのでしっかり煮て',
            },
            {
                text: '豆腐を加えてひと煮立ちしたら火を止め、味噌を溶き入れます。ねぎを散らして完成！',
                emoji: '✨',
                tip: '味噌は沸騰させると風味が飛ぶので、必ず火を止めてから',
            },
        ],
        tips: [
            '数種類のきのこを混ぜると旨味が倍増',
            'わかめや油揚げを足しても美味しい',
            '仕上げにすりごまを入れるとコクが出る',
        ],
    },
    {
        id: 16,
        name: 'ウインナーとパプリカのケチャップ炒め',
        emoji: '🌭',
        time: 5,
        difficulty: 'かんたん',
        servings: '2人分',
        description: '子どもも大好き！カラフルで食欲をそそるケチャップ炒め。お弁当のおかずにも。',
        ingredients: ['sausage', 'paprika', 'onion', 'ketchup'],
        ingredientDetails: [
            { name: 'ウインナー', amount: '6本', icon: '🌭' },
            { name: 'パプリカ', amount: '1個', icon: '🫑' },
            { name: '玉ねぎ', amount: '1/2個', icon: '🧅' },
            { name: 'ケチャップ', amount: '大さじ2', icon: '🧴' },
            { name: 'ウスターソース', amount: '小さじ1', icon: '🧴' },
            { name: 'オリーブオイル', amount: '大さじ1', icon: '🫒' },
        ],
        steps: [
            {
                text: 'ウインナーに斜めに切り込みを入れます。パプリカと玉ねぎを細切りにします。',
                emoji: '🔪',
                tip: '切り込みを入れるとウインナーが開いて見た目もかわいく',
            },
            {
                text: 'フライパンにオリーブオイルを引き、中火でウインナーを炒め、焼き色がついたら野菜を加えます。',
                emoji: '🌭',
                tip: 'ウインナーを先に焼くと旨味の油が出て野菜も美味しくなる',
            },
            {
                text: '野菜がしんなりしたらケチャップとウスターソースを加えて絡めたら完成！',
                emoji: '✨',
                tip: 'ケチャップは少し焦がし気味に炒めると香ばしくなる',
            },
        ],
        tips: [
            'ピーマンを加えても合う',
            'カレー粉を少し足すとスパイシーに',
            'パンに挟んでホットドッグ風にもアレンジ可能',
        ],
    },
    {
        id: 17,
        name: 'めんつゆで簡単きゅうりの浅漬け',
        emoji: '🥒',
        time: 5,
        difficulty: 'かんたん',
        servings: '2人分',
        description: 'めんつゆに漬けるだけ！さっぱり味の即席浅漬け。箸休めやおつまみに最高。',
        ingredients: ['cucumber', 'mentsuyu', 'sesame-oil', 'ginger'],
        ingredientDetails: [
            { name: 'きゅうり', amount: '2本', icon: '🥒' },
            { name: 'めんつゆ（2倍濃縮）', amount: '大さじ3', icon: '🫗' },
            { name: 'ごま油', amount: '小さじ1', icon: '🫒' },
            { name: '生姜', amount: '少々', icon: '🫚' },
            { name: '白ごま', amount: '適量', icon: '🧂' },
        ],
        steps: [
            {
                text: 'きゅうりを麺棒やコップの底で叩いて割り、一口大にちぎります。',
                emoji: '🥒',
                tip: '叩いて割ると味が染み込みやすくなる。包丁で切るより断然おいしい！',
            },
            {
                text: 'ポリ袋にきゅうり・めんつゆ・ごま油・おろし生姜を入れてもみ込みます。',
                emoji: '🫗',
                tip: '空気を抜いて口を閉じると味が均一に浸かる',
            },
            {
                text: '冷蔵庫で5分以上置き、器に盛って白ごまをふったら完成！',
                emoji: '✨',
                tip: '長く漬けるほど味が染みるので、余裕があれば30分以上漬けても',
            },
        ],
        tips: [
            'ラー油を足すとピリ辛でおつまみ向きに',
            '大葉やミョウガを加えると夏にぴったりの爽やかさ',
            '翌日はさらに味が染みて美味しい',
        ],
    },
    {
        id: 18,
        name: '牛肉とピーマンのオイスター炒め',
        emoji: '🥩',
        time: 8,
        difficulty: 'ふつう',
        servings: '2人分',
        description: '中華の定番・青椒肉絲風！シャキシャキピーマンと牛肉の旨味がたまらない一皿。',
        ingredients: ['beef', 'pepper', 'garlic', 'soy-sauce', 'sesame-oil'],
        ingredientDetails: [
            { name: '牛こま切れ肉', amount: '150g', icon: '🥩' },
            { name: 'ピーマン', amount: '3個', icon: '🫑' },
            { name: 'にんにく', amount: '1片', icon: '🧄' },
            { name: '醤油', amount: '大さじ1', icon: '🫗' },
            { name: 'ごま油', amount: '大さじ1', icon: '🫒' },
            { name: 'オイスターソース', amount: '大さじ1', icon: '🧴' },
            { name: '酒', amount: '大さじ1', icon: '🍶' },
            { name: '片栗粉', amount: '小さじ1', icon: '🧂' },
        ],
        steps: [
            {
                text: '牛肉に酒と片栗粉をもみ込みます。ピーマンは縦に細切り、にんにくはみじん切りに。',
                emoji: '🔪',
                tip: '片栗粉をまぶすと肉が柔らかくジューシーに仕上がる',
            },
            {
                text: 'フライパンにごま油とにんにくを入れて中火。香りが出たら牛肉を広げて焼き、色が変わったら一度取り出します。',
                emoji: '🥩',
                tip: '牛肉は広げて焼くと香ばしく仕上がる',
            },
            {
                text: 'ピーマンを強火でサッと1分炒め、牛肉を戻してオイスターソース・醤油を加えて絡めたら完成！',
                emoji: '✨',
                tip: 'ピーマンは炒めすぎないのがシャキシャキのコツ',
            },
        ],
        tips: [
            'たけのこ水煮を加えると本格的な青椒肉絲に',
            'パプリカで代用するとカラフルに',
            'ごはんにのせて丼にしても美味しい',
        ],
    },
];
